version: '3'
services:

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: keycloak
    networks:
      - common
    tty: true
    stdin_open: true
    ports:
      - 18080:8080
    volumes:
      - ./data/keycloak:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passwd
    command:
      - start-dev

  apps:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ../:/offlineToken:cached
    working_dir: /offlineToken
    command: sleep infinity

networks:
  common:
